name: Build UF2s

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      sdk_tools_version:
        description: 'Custom Pico SDK Tools version'
        required: false
        type: string
      pico_sdk_tag:
        description: 'Custom Pico SDK tag'
        required: false
        type: string
      pico_examples_tag:
        description: 'Custom Pico Examples tag'
        required: false
        type: string
      pico_sdk_repo:
        description: 'Custom Pico SDK repo'
        required: false
        type: string
      pico_examples_repo:
        description: 'Custom Pico Examples repo'
        required: false
        type: string

permissions:
  contents: write

env:
  SDK_TOOLS_VERSION: ${{ inputs.sdk_tools_version != '' && inputs.sdk_tools_version || '2.2.0' }}
  PICO_SDK_TAG: ${{ inputs.pico_sdk_tag != '' && inputs.pico_sdk_tag || '2.2.0' }}
  PICO_EXAMPLES_TAG: ${{ inputs.pico_examples_tag != '' && inputs.pico_examples_tag || 'sdk-2.2.0' }}
  PICO_SDK_REPO: ${{ inputs.pico_sdk_repo != '' && inputs.pico_sdk_repo || 'raspberrypi/pico-sdk' }}
  PICO_EXAMPLES_REPO: ${{ inputs.pico_examples_repo != '' && inputs.pico_examples_repo || 'raspberrypi/pico-examples' }}

jobs:
  build-uf2s:
    name: Build UF2s
    runs-on: ubuntu-latest
    # Prevent running twice for PRs from same repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Print environment
        run: |
          echo "SDK_TOOLS_VERSION=${{ env.SDK_TOOLS_VERSION }}"
          echo "PICO_SDK_TAG=${{ env.PICO_SDK_TAG }}"
          echo "PICO_EXAMPLES_TAG=${{ env.PICO_EXAMPLES_TAG }}"
          echo "PICO_SDK_REPO=${{ env.PICO_SDK_REPO }}"
          echo "PICO_EXAMPLES_REPO=${{ env.PICO_EXAMPLES_REPO }}"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt install cmake ninja-build python3 build-essential libusb-1.0-0-dev
      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v5
        with:
          path: |
            arm-toolchain
            riscv-toolchain
            picotool
            pico-sdk-tools
          key: ${{ runner.os }}-${{ runner.arch }}-${{ env.SDK_TOOLS_VERSION }}-toolchains
      - name: Install Toolchains & Tools
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: ./download_extract_tools.sh ${{ env.SDK_TOOLS_VERSION }}
      - name: Checkout Pico SDK
        uses: actions/checkout@v6
        with:
          repository: ${{ env.PICO_SDK_REPO }}
          ref: ${{ env.PICO_SDK_TAG }}
          path: pico-sdk
          submodules: 'recursive'
      - name: Checkout Pico Examples
        uses: actions/checkout@v6
        with:
          repository: ${{ env.PICO_EXAMPLES_REPO }}
          ref: ${{ env.PICO_EXAMPLES_TAG }}
          path: pico-examples
      - name: Build Universal UF2s
        run: |
          cmake -S pico-examples -B build-universal -G "Ninja" \
            -D PICO_SDK_PATH="${{ github.workspace }}/pico-sdk" \
            -D PICO_TOOLCHAIN_PATH="${{ github.workspace }}/arm-toolchain" \
            -D PICO_ARM_TOOLCHAIN_PATH="${{ github.workspace }}/arm-toolchain" \
            -D PICO_RISCV_TOOLCHAIN_PATH="${{ github.workspace }}/riscv-toolchain" \
            -D picotool_DIR="${{ github.workspace }}/picotool/picotool" \
            -D pioasm_DIR="${{ github.workspace }}/pico-sdk-tools/pioasm"
          cmake --build build-universal --target hello_universal blink_universal nuke_universal
      - name: Upload UF2s
        uses: actions/upload-artifact@v6
        with:
          name: uf2s
          path: |
            build-universal/universal/blink_universal/blink_universal.uf2
            build-universal/universal/hello_universal/hello_universal.uf2
            build-universal/universal/nuke_universal/nuke_universal.uf2
      - name: Add Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build-universal/universal/blink_universal/blink_universal.uf2
            build-universal/universal/hello_universal/hello_universal.uf2
            build-universal/universal/nuke_universal/nuke_universal.uf2
