name: Build UF2s

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tools_version:
        description: 'Tools version'
        required: true
        default: '2.2.0'
        type: string
      sdk_tag:
        description: 'SDK tag'
        required: true
        default: '2.2.0'
        type: string
      examples_tag:
        description: 'Examples tag'
        required: true
        default: 'sdk-2.2.0'
        type: string

permissions:
  contents: write

env:
  TOOLS_VERSION: ${{ inputs.tools_version }}
  SDK_TAG: ${{ inputs.sdk_tag }}
  EXAMPLES_TAG: ${{ inputs.examples_tag }}

jobs:
  build-uf2s:
    name: Build UF2s
    runs-on: ubuntu-latest
    # Prevent running twice for PRs from same repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install cmake ninja-build python3 build-essential libusb-1.0-0-dev
      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v5
        with:
          path: arm-toolchain riscv-toolchain picotool pico-sdk-tools
          key: ${{ runner.os }}-${{ env.TOOLS_VERSION }}-toolchains
      - name: Install Toolchains & Tools
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: download_extract_tools.sh ${{ env.TOOLS_VERSION }}
      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: ${{ env.SDK_TAG }}
          path: pico-sdk
          submodules: 'recursive'
      - name: Checkout Pico Examples
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-examples
          ref: ${{ env.EXAMPLES_TAG }}
          path: pico-examples
      - name: Build Universal UF2s
        run: |
          cmake -S pico-examples -B build-universal -G "Ninja" -D PICO_SDK_PATH="${{ github.workspace }}/pico-sdk" -D PICO_TOOLCHAIN_PATH="${{ github.workspace }}/arm-toolchain" -D PICO_ARM_TOOLCHAIN_PATH="${{ github.workspace }}/arm-toolchain" -D PICO_RISCV_TOOLCHAIN_PATH="${{ github.workspace }}/riscv-toolchain" -D picotool_DIR="${{ github.workspace }}/picotool/picotool" -D pioasm_DIR="${{ github.workspace }}/pico-sdk-tools/pioasm"
          cmake --build build-universal --target hello_universal blink_universal nuke_universal
      - name: Upload UF2s
        uses: actions/upload-artifact@v4
        with:
          name: uf2s
          path: |
            build-universal/universal/blink_universal/blink_universal.uf2
            build-universal/universal/hello_universal/hello_universal.uf2
            build-universal/universal/nuke_universal/nuke_universal.uf2
      - name: Add Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build-universal/universal/blink_universal/blink_universal.uf2
            build-universal/universal/hello_universal/hello_universal.uf2
            build-universal/universal/nuke_universal/nuke_universal.uf2
